export const GET_SITE_STATUS_PENDING = 'GET_SITE_STATUS_PENDING';
export const GET_SITE_STATUS_FAILED = 'GET_SITE_STATUS_FAILED';
export const GET_SITE_STATUS_SUCCEEDED = 'GET_SITE_STATUS_SUCCEEDED';
export const GET_SITES = 'GET_SITES';
